# Generated by Django 5.2.12 on 2026-03-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_levels', '0001_initial'),
        ('school_years', '0001_initial'),
        ('sections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('guardian_first_name', models.CharField(max_length=50)),
                ('guardian_mid_name', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_last_name', models.CharField(max_length=50)),
                ('guardian_contact', models.CharField(max_length=15)),
                ('relationship', models.CharField(choices=[('Parent', 'Parent'), ('Guardian', 'Guardian'), ('Other', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('end_of_year_status', models.CharField(blank=True, choices=[('Promoted', 'Promoted'), ('Retained', 'Retained'), ('Dropped', 'Dropped'), ('Graduated', 'Graduated')], max_length=20, null=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grade_levels.gradelevel')),
                ('next_grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_grade_enrollments', to='grade_levels.gradelevel')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_years.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sections.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'db_table': 'student_enrollments',
            },
        ),
    ]
