# Generated by Django 5.2.12 on 2026-04-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=20)),
                ('paces_behind', models.IntegerField(default=0)),
                ('pace_percent', models.FloatField(default=0.0)),
                ('attendance', models.FloatField(default=0.0, help_text='Attendance percentage')),
                ('status', models.CharField(choices=[('Critical', 'Critical'), ('At Risk', 'At Risk'), ('Warning', 'Warning'), ('On Track', 'On Track')], max_length=20)),
                ('trend', models.CharField(choices=[('declining', 'Declining'), ('stable', 'Stable'), ('improving', 'Improving')], max_length=20)),
                ('last_activity', models.CharField(default='Today', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='early_warnings', to='students.studentenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_warnings', to='students.student')),
            ],
            options={
                'db_table': 'early_warnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('pace_percent', models.FloatField(default=0.0, help_text='Percentage of curriculum completed')),
                ('paces_behind', models.IntegerField(default=0, help_text='Number of paces behind standard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paces', to='students.studentenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paces', to='students.student')),
            ],
            options={
                'db_table': 'student_paces',
                'ordering': ['-updated_at'],
            },
        ),
    ]
