# Generated by Django 6.0.3 on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_pace', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0005_teacheravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_logs', to='students.student')),
                ('student_pace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_logs', to='student_pace.studentpace')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_logs', to='teachers.teacher')),
            ],
            options={
                'db_table': 'data_quality_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
