# Generated by Django 6.0.3 on 2026-03-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacheravailability_teacherassignment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacheravailability',
            name='unique_teacher_availability_slot',
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
    ]
