# Generated by Django 6.0.3 on 2026-03-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_teacheravailability_unique_teacher_availability_slot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherassignment',
            name='unique_teacher_subject_section_school_year',
        ),
        migrations.RemoveField(
            model_name='teacherassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacherassignment',
            name='updated_at',
        ),
    ]
