# Generated by Django 6.0.3 on 2026-03-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classschedule',
            name='unique_section_day_start_time',
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, unique=True),
        ),
    ]
